version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: master_project_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

volumes: {}