version: '3.8'

services:
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: master_project_prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   depends_on:
  #     - backend
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: master_project_grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus
  # backend:
  #     build:
  #       context: ./backend
  #       dockerfile: Dockerfile
  #     container_name: master_project_backend
  #     ports:
  #       - "8080:8080"
  #     environment:
  #       - ASPNETCORE_ENVIRONMENT=Development
  #       - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ecommerce_db;Username=admin;Password=admin123
  #     depends_on:
  #       - postgres
  postgres:
    image: postgres:15
    container_name: master_project_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

volumes: 
  prometheus_data:
  grafana_data: